name: Build and Deploy Hugo Site

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Hugo
        run: |
          wget -O hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.145.0/hugo_extended_0.145.0_Linux-64bit.tar.gz
          tar -xzf hugo.tar.gz
          sudo mv hugo /usr/local/bin/
          hugo version

      - name: Build Hugo Site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          folder: public
          clean: false